In [56]:
import numpy as np

from aux.web import *
from aux.input import *
from aux.output import *
from common.tools import *
from common.rng import *
from game.solution import get_solution

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [140]:
problem_id = 0
tag = 'T'

problem, seeds = parse_problem(load_problem(problem_id))

In [147]:
solutions = []
for seed in seeds:
    commands = get_solution(problem, seed, '')
    solutions += [output_solution(problem_id, seed, commands, tag)]
s = combine_solutions(solutions)
print(s)

Generating on depth 1
LM: None
  Creating move with dir: 20 [1, 2, 0, 3]
  Creating move with dir: 20 [0, 3, 1, 2]
  Creating move with dir: 10 [3, 2, 3, 2]
  Creating move with dir: 10 [2, 3, 2, 3]
Score: 1.0
Directions: [1, 2, 0, 3]
Generating on depth 1
LM: 3
  Creating move with dir: 18 [1, 2, 0, 3]
  Creating move with dir: 17 [0, 3, 1, 2]
  Creating move with dir: 9 [3, 2, 3, 2]
  Creating move with dir: 9 [2, 3, 2, 3]
Score: 2.0
Directions: [3, 2, 3, 2]
Generating on depth 1
LM: 3
  Creating move with dir: 12 [1, 2, 0, 3]
  Creating move with dir: 12 [0, 3, 1, 2]
  Creating move with dir: 6 [3, 2, 3, 2]
  Creating move with dir: 6 [2, 3, 2, 3]
Score: 5.0
Directions: [1, 2, 0, 3]
Generating on depth 1
LM: 3
  Creating move with dir: 11 [1, 2, 0, 3]
  Creating move with dir: 9 [0, 3, 1, 2]
  Creating move with dir: 7 [3, 2, 3, 2]
  Creating move with dir: 5 [2, 3, 2, 3]
Score: 8.0
Directions: [3, 2, 3, 2]
Generating on depth 1
LM: 3
  Creating move with dir: 7 [1, 2, 0, 3]
  Creat

In [148]:
seed = 0
commands = get_solution(problem, seed, '')

Generating on depth 1
LM: None
  Creating move with dir: 20 [1, 2, 0, 3]
  Creating move with dir: 20 [0, 3, 1, 2]
  Creating move with dir: 10 [3, 2, 3, 2]
  Creating move with dir: 10 [2, 3, 2, 3]
Score: 1.0
Directions: [1, 2, 0, 3]
Generating on depth 1
LM: 3
  Creating move with dir: 18 [1, 2, 0, 3]
  Creating move with dir: 17 [0, 3, 1, 2]
  Creating move with dir: 9 [3, 2, 3, 2]
  Creating move with dir: 9 [2, 3, 2, 3]
Score: 2.0
Directions: [3, 2, 3, 2]
Generating on depth 1
LM: 3
  Creating move with dir: 12 [1, 2, 0, 3]
  Creating move with dir: 12 [0, 3, 1, 2]
  Creating move with dir: 6 [3, 2, 3, 2]
  Creating move with dir: 6 [2, 3, 2, 3]
Score: 5.0
Directions: [1, 2, 0, 3]
Generating on depth 1
LM: 3
  Creating move with dir: 11 [1, 2, 0, 3]
  Creating move with dir: 9 [0, 3, 1, 2]
  Creating move with dir: 7 [3, 2, 3, 2]
  Creating move with dir: 5 [2, 3, 2, 3]
Score: 8.0
Directions: [3, 2, 3, 2]
Generating on depth 1
LM: 3
  Creating move with dir: 7 [1, 2, 0, 3]
  Creat

In [149]:
upload_solution(s)

In [150]:
with open('../../submissions/0_T.json', 'w') as f:
    f.write(s)

In [151]:
print(len(commands))
print(commands)

70
[1, 2, 0, 3, 1, 2, 0, 3, 1, 2, 0, 3, 1, 2, 0, 3, 1, 2, 0, 3, 3, 2, 3, 2, 3, 2, 3, 2, 3, 1, 2, 0, 3, 1, 2, 0, 3, 1, 2, 0, 3, 3, 2, 3, 2, 3, 2, 3, 1, 2, 0, 3, 1, 2, 0, 3, 2, 3, 2, 3, 2, 1, 2, 0, 3, 1, 3, 2, 3, 2]


In [152]:
output_solution(problem_id, seed, commands, tag)

[1, 2, 0, 3, 1, 2, 0, 3, 1, 2, 0, 3, 1, 2, 0, 3, 1, 2, 0, 3, 3, 2, 3, 2, 3, 2, 3, 2, 3, 1, 2, 0, 3, 1, 2, 0, 3, 1, 2, 0, 3, 3, 2, 3, 2, 3, 2, 3, 1, 2, 0, 3, 1, 2, 0, 3, 2, 3, 2, 3, 2, 1, 2, 0, 3, 1, 3, 2, 3, 2]


{'problemId': 0,
 'seed': 0,
 'solution': 'baplbaplbaplbaplbapllalalalalbaplbaplbapllalalalbaplbaplalalabaplblala',
 'tag': 'T'}

In [146]:
seed = 17
for _ in range(10):
    seed, n = next_number(seed)
    print(n)

0
24107
16552
12125
9427
13152
21440
3383
6873
16117


In [155]:
c3 = np.array([[-1, 0, 1], [0, 0, 0], [0, 1, (-1)]], dtype='int32')
c2 = np.array([[-1, -1], [-1, 1], [0, 0]], dtype='int32')

print(points2hex(c2))
print(hex2points(c3))


[[ 0  1 -1]
 [-1  0  1]
 [ 0  0  0]]
[[-1  1]
 [ 0  0]
 [-1 -1]]
